name: Build Looky APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04 # Используем конкретную версию Ubuntu

    steps:
      - uses: actions/checkout@v4

      - name: Get Date
        id: get-date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Build with Buildozer
        # Используем альтернативный экшен, он стабильнее
        uses: akshayaurora/buildozer-action@master
        with:
          buildozer_version: master
          command: buildozer android debug
          repository_root: .

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Looky-Package
          path: bin/*.apk
